name: pgkyl
channels:
  - defaults
  - conda-forge
dependencies:
  - click>=8.1.7
  - matplotlib>=3.7.0
  - msgpack-python>=1.0.3
  - numpy>=1.24.4,<2
  - pytables>=3.8.0
  - pytest>=7.4.0
  - python>=3.11
  - scipy>=1.10.1
  - sympy>=1.12
  - plotly>=6.6.0
  - python-kaleido>=1.2.0
  - pyvista>=0.47.3 # Must update when my bug gets patched: Also must fix this "Factor" and set to 1. pyvista[jupyter]
  - h5py
