package:
  name: postgkyl
  version: 1.7.0

source:
  path: ./

channels:
  - gkyl

build:
  number: {{ CUSTOM_BUILD_NUMBER }}
  always_include_files:
    - postgkyl/data/xformMatricesModalMaximal.h5
    - postgkyl/data/xformMatricesModalSerendipity.h5
    - postgkyl/data/xformMatricesNodalSerendipity.h5
    - postgkyl/output/postgkyl.mplstyle
  entry_points:
    - pgkyl = postgkyl.pgkyl:cli

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy
    - scipy
    - matplotlib
    - pytables
    - click
    - sympy
    - conda-forge::adios2=2.9.1
    - msgpack-python

test:
  imports:
    - postgkyl

about:
  home: https://github.com/ammarhakim/postgkyl
  license: BSD
  license_file: LICENSE
