package:
  name: postgkyl
  version: "0.2.2"

source:
  path: ./

build:
  always_include_files:
    - postgkyl/data/xformMatricesModalMaximal.h5
    - postgkyl/data/xformMatricesModalSerendipity.h5
    - postgkyl/data/xformMatricesNodalSerendipity.h5

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy >=1.11
    - scipy
    - matplotlib >=2.0
    - pytables

test:
  imports:
    - postgkyl

about:
  home: https://bitbucket.org/ammarhakim/postgkyl
  license: BSD
  license_file: LICENSE