package:
  name: postgkyl
  version: "0.1.1"

source:
  path: ./

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy >=1.11
    - scipy
    - matplotlib
    - pytables

test:
  imports:
    - postgkyl

about:
  home: https://bitbucket.org/ammarhakim/postgkyl
  license: BSD
  license_file: LICENSE