package:
  name: postgkyl
  version: "1.5"

source:
  path: ./

build:
  number: 20200331
  always_include_files:
    - postgkyl/data/xformMatricesModalMaximal.h5
    - postgkyl/data/xformMatricesModalSerendipity.h5
    - postgkyl/data/xformMatricesNodalSerendipity.h5
    - postgkyl/output/postgkyl.mplstyle
  entry_points:
    - pgkyl = postgkyl.pgkyl:cli

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy >=1.13
    - scipy
    - matplotlib >=3.1
    - pytables
    - click
    - sympy
    - adiospy
    - bokeh

test:
  imports:
    - postgkyl

about:
  home: https://github.com/ammarhakim/postgkyl
  license: BSD
  license_file: LICENSE