package:
  name: postgkyl
  version: "0.9.6"

source:
  path: ./

build:
  always_include_files:
    - postgkyl/data/xformMatricesModalMaximal.h5
    - postgkyl/data/xformMatricesModalSerendipity.h5
    - postgkyl/data/xformMatricesNodalSerendipity.h5
    - postgkyl/commands/postgkyl.mplstyle
  entry_points:
    - pgkyl = postgkyl.pgkyl:cli

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy >=1.11
    - scipy
    - matplotlib >=2.0
    - pytables
    - click
    - sympy
    - adiospy

test:
  imports:
    - postgkyl

about:
  home: https://bitbucket.org/ammarhakim/postgkyl
  license: BSD
  license_file: LICENSE