package:
  name: postgkyl
  version: "1.6.7"

source:
  path: ./

channels:
    - defaults
    - gkyl

build:
  number: 20210811
  always_include_files:
    - postgkyl/data/xformMatricesModalMaximal.h5
    - postgkyl/data/xformMatricesModalSerendipity.h5
    - postgkyl/data/xformMatricesNodalSerendipity.h5
    - postgkyl/output/postgkyl.mplstyle
  entry_points:
    - pgkyl = postgkyl.pgkyl:cli

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy>=1.16
    - scipy
    - matplotlib>=3.1
    - pytables
    - click
    - sympy
    - bokeh
    - adiospy
    - msgpack-python

test:
  imports:
    - postgkyl

about:
  home: https://github.com/ammarhakim/postgkyl
  license: BSD
  license_file: LICENSE
