
name: Test Postgkyl

on: [workflow_dispatch, push]

jobs:
  install_and_test:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
    - uses: actions/checkout@v3
    - uses: FedericoCarboni/setup-ffmpeg@v3
      id: setup-ffmpeg
      with:
        ffmpeg-version: release
    - name: Setup conda
      uses: s-weigand/setup-conda@v1
      with:
        update-conda: true
        python-version: ${{ matrix.python-version }}
        conda-channels: anaconda, conda-forge
    - name: Install dependencies
      run: |
        conda update conda
        conda env update --file environment.yml --name base
    - name: Install postgkyl
      run: |
        pip install -e .
    - name: Test with pytest
      run: |
        pytest
